# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 1
  - name: Research
    url: '/research/'
    weight: 2
  - name: Members
    url: '/people/'
    weight: 3
  - name: Publication
    url: '/publication/'
    weight: 4
  - name: News
    url: '/news/'
    weight: 5
  - name: Contact
    url: '/contact/'
    weight: 6

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
  - identifier: community
    name: "Community"
    pageRef: "/community"
    weight: 2
  - identifier: hugoDocs
    name: "Hugo Docs ↗"
    url: "https://docs.hugoblox.com"
    weight: 3
